type Mutation {
  self: SelfMutation! @auth(object: "self", action: "mutate")
  auth: AuthMutation! @auth(object: "auth", action: "mutate")
  torrent: TorrentMutation! @auth(object: "torrent", action: "mutate")
  queue: QueueMutation! @auth(object: "queue", action: "mutate")
}

type TorrentMutation {
  delete(infoHashes: [Hash20!]!): Void
    @auth(object: "torrent", action: "delete")
  putTags(infoHashes: [Hash20!]!, tagNames: [String!]!): Void
  setTags(infoHashes: [Hash20!]!, tagNames: [String!]!): Void
  deleteTags(infoHashes: [Hash20!], tagNames: [String!]): Void
  reprocess(input: TorrentReprocessInput!): Void
}

input TorrentReprocessInput {
  infoHashes: [Hash20!]!
  classifierRematch: Boolean
  classifierWorkflow: String
  apisDisabled: Boolean
  localSearchDisabled: Boolean
}
