package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"time"

	"github.com/bitmagnet-io/bitmagnet/internal/auth/rbac"
	"github.com/bitmagnet-io/bitmagnet/internal/gql"
	"github.com/bitmagnet-io/bitmagnet/internal/gql/gqlmodel"
	"github.com/bitmagnet-io/bitmagnet/internal/gql/gqlmodel/gen"
	"github.com/bitmagnet-io/bitmagnet/internal/model"
	"github.com/bitmagnet-io/bitmagnet/internal/slice"
)

// Permissions is the resolver for the permissions field. It reports what the
// key was scoped to, which is a property of the key and does not move when the
// owning user's role does. What the key can currently reach is Self.permissions.
func (r *aPIKeyResolver) Permissions(_ context.Context, obj *model.APIKey) ([]gen.AuthObjectAction, error) {
	return gqlmodel.ObjectActionsToGql(
		slice.Map(obj.Permissions, func(perm model.APIKeyPermission) rbac.ObjectAction {
			return rbac.NewObjectAction(perm.Namespace, perm.Object, perm.Action)
		}),
	), nil
}

// ExpiresAt is the resolver for the expiresAt field.
func (r *aPIKeyResolver) ExpiresAt(ctx context.Context, obj *model.APIKey) (*time.Time, error) {
	return gqlmodel.NullTimePtr(obj.ExpiresAt), nil
}

// Role is the resolver for the role field.
func (r *invitationResolver) Role(ctx context.Context, obj *model.Invitation) (string, error) {
	return obj.RoleName, nil
}

// CreatedBy is the resolver for the createdBy field.
func (r *invitationResolver) CreatedBy(ctx context.Context, obj *model.Invitation) (*model.User, error) {
	// The relation is a value, not a pointer, so it is only meaningful when the
	// nullable foreign key is actually set.
	if !obj.CreatedBy.Valid {
		return nil, nil
	}

	user := obj.CreatedByUser

	return &user, nil
}

// ClaimedBy is the resolver for the claimedBy field.
func (r *invitationResolver) ClaimedBy(ctx context.Context, obj *model.Invitation) (*model.User, error) {
	if !obj.ClaimedBy.Valid {
		return nil, nil
	}

	user := obj.ClaimedByUser

	return &user, nil
}

// ExpiresAt is the resolver for the expiresAt field.
func (r *invitationResolver) ExpiresAt(ctx context.Context, obj *model.Invitation) (*time.Time, error) {
	return gqlmodel.NullTimePtr(obj.ExpiresAt), nil
}

// Role is the resolver for the role field.
func (r *userResolver) Role(ctx context.Context, obj *model.User) (string, error) {
	return obj.RoleName, nil
}

// LastLoginAt is the resolver for the lastLoginAt field.
func (r *userResolver) LastLoginAt(ctx context.Context, obj *model.User) (*time.Time, error) {
	return gqlmodel.NullTimePtr(obj.LastLoginAt), nil
}

// APIKey returns gql.APIKeyResolver implementation.
func (r *Resolver) APIKey() gql.APIKeyResolver { return &aPIKeyResolver{r} }

// Invitation returns gql.InvitationResolver implementation.
func (r *Resolver) Invitation() gql.InvitationResolver { return &invitationResolver{r} }

// User returns gql.UserResolver implementation.
func (r *Resolver) User() gql.UserResolver { return &userResolver{r} }

type (
	aPIKeyResolver     struct{ *Resolver }
	invitationResolver struct{ *Resolver }
	userResolver       struct{ *Resolver }
)
